### ISSUE TITLE
`CSP-3` is misleading

### ISSUE THREAD

**Issue by fgauna12** [boxboat/aks-health-check#50]
The check says to "Enable Azure AD integration" but it's really checking for AKS-managed AAD.

For example, it failed for this one.

![image](https://user-images.githubusercontent.com/1071270/120651130-6f5f3080-c44c-11eb-8836-c661f0492273.png)
![image](https://user-images.githubusercontent.com/1071270/120651149-76863e80-c44c-11eb-8028-695905b5962e.png)

**Comment by PixelRobots** [comment]
When you look at the MS docs (https://docs.microsoft.com/en-us/azure/aks/managed-aad) the heading AKS-managed Azure Active Directory integration. So, I don't think it is misleading. but for people new to AKS I can see the confusion. Perhaps it should be "Enabled Azure AD integration (AKS-managed)"

**Comment by brian-workman** [comment]
Agreed. This was one of those things where the wording is kinda confusing because they overlap the terms so much between cluster auth and using Azure AD for cluster RBAC. 'Azure AD Integration' is probably too ambiguous to figure out which of those 2 we're referring to. Maybe mentioning 'Cluster Auth' or 'Cluster Login' or something would help make that more clear. 'Enable Managed Azure AD Integration for Cluster Authentication' or something along those lines.

Although reading that, it's a little wordy. Words are hard. =]

**Comment by PixelRobots** [comment]
Yes they are, I was thinking, maybe where possible we can add links to the ms docs, just a simple bit.ly link under the heading or something, so people can check to see what it relates to?

**Comment by brian-workman** [comment]
Links to the docs are on the accompanying template for now, but it's definitely possible in the future the app could generate an actual HTML report or something with the documentation linked.

**Comment by PixelRobots** [comment]
Yeah that would be good. The link to the doc via the container image does not actually work by the way.

**Comment by brian-workman** [comment]
Good eyes! I blew it up at one point in the past and we updated on the README. Just created a PR to update in code.
